module.exports = {
	plugins: ["simple-import-sort", "import", "unused-imports"],
	rules: {
		"import/first": "error",
		"import/newline-after-import": "error",
		"import/no-duplicates": "error",
		"import/no-unresolved": "error",
		"import/no-webpack-loader-syntax": "error",
		"prettier/prettier": [
			"error",
			{
				arrowParens: "always",
				bracketSameLine: false,
				bracketSpacing: true,
				semi: true,
				experimentalTernaries: false,
				singleQuote: false,
				jsxSingleQuote: false,
				quoteProps: "as-needed",
				trailingComma: "es5",
				singleAttributePerLine: true,
				htmlWhitespaceSensitivity: "css",
				vueIndentScriptAndStyle: true,
				proseWrap: "preserve",
				insertPragma: false,
				printWidth: 120,
				requirePragma: false,
				tabWidth: 4,
				useTabs: true,
				embeddedLanguageFormatting: "auto",
				endOfLine: "lf",
			},
		],
		"simple-import-sort/exports": "error",
		"simple-import-sort/imports": "error",
		"unused-imports/no-unused-imports": "error",
		"unused-imports/no-unused-vars": [
			"warn",
			{
				vars: "all",
				varsIgnorePattern: "^_",
				args: "after-used",
				argsIgnorePattern: "^_",
			},
		],
	},
};
