name: Publish in NPM

on:
  push:
    branches:
      - main

jobs:
  npm-publish:
    runs-on: ubuntu-latest
    environment: NPM
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'pnpm'
          registry-url: 'https://registry.npmjs.org/'
      - name: Install dependencies
        run: pnpm install
      - name: Run tests
        run: pnpm test
      - uses: JS-DevTools/npm-publish@v3
        with:
          token: ${{ secrets.TOKEN_NPM }}
