name: Publish in NPM

on:
  push:
    branches:
      - main

jobs:
  npm-publish:
    runs-on: ubuntu-latest
    environment: NPM
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'pnpm'
      - name: Install dependencies
        run: pnpm install
      - name: Run tests
        run: pnpm test
      - name: Publish to npm
        run: npm publish --access public
        env:
          npm_config_//registry.npmjs.org/:_authToken: ${{ secrets.TOKEN_NPM }}
