name: 'Publish in NPM'

on:
  push:
    branches:
      - main

jobs:
  npm-publish:
    runs-on: ubuntu-latest
    environment: NPM
    steps:
      - uses: actions/checkout@v4.1.2
      - uses: pnpm/action-setup@v3
        with:
          version: 8
      - name: Setup Node
        uses: actions/setup-node@v4.0.2
        with:
          node-version: '20'
          cache: 'pnpm'
          registry-url: 'https://registry.npmjs.org/' 
      - name: Install dependencies
        run: |
            pnpm install
      - uses: JS-DevTools/npm-publish@v3.1.1
        with:
          token: ${{ secrets.TOKEN_NPM }}
